MemoryClassLoader周りの修正および疑惑値算出の高速化
posl/jProphet pull request #109
Opened 2020-05-10 12:36 UTC by kyamatek

2020-05-17 01:03 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            int numberOfSuccessedTestsNotCoveringStatement = successedCoverageStatus.get(1) == null ? 0 : successedCoverageStatus.get(1);
final

2020-05-17 01:04 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            int numberOfSuccessedTestsNotCoveringStatement = successedCoverageStatus.get(1) == null ? 0 : successedCoverageStatus.get(1);
get(1)とかget(2)とかが何をしているのかとても分かりづらいのでStatusのenumを使った方がいい

2020-05-17 01:09 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            int numberOfSuccessedTestsNotCoveringStatement = successedCoverageStatus.get(1) == null ? 0 : successedCoverageStatus.get(1);
nullになるのはどういう時？

2020-05-17 09:12 UTC, kyamatek commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +        }
逆になってました，ありがとうございます．
kGenprogではテストコードをinstrumentせずにjunitで実行していたので，このように変更しました．

2020-05-17 09:15 UTC, kyamatek commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +
消し忘れていました

2020-05-17 09:22 UTC, kyamatek commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +            final TestResult testResult = new TestResult(testMethodFQN, wasFailed, coverages);
Descriptionを介すと失敗するはずのテストが一部成功扱いになっていたので変更しました．kGenprogでも同じ理由でリスナーのフィールドに直接結果を書き込むように変更してたので参考にしました．
https://github.com/kusumotolab/kGenProg/issues/288

2020-05-17 09:30 UTC, kyamatek commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +        for (int i = 1; i <= lineLength; i++) {
Iをlineに変えると
`Map<Integer, Integer> failedCoverageStatus = failedCoverages.stream()
                .map(c -> c.getStatusOfLine().get(line))`
のmapの中のlineをfinalにしてくださいという警告が出たのでこの形にしてます．

2020-05-17 09:44 UTC, kyamatek commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            int numberOfSuccessedTestsNotCoveringStatement = successedCoverageStatus.get(1) == null ? 0 : successedCoverageStatus.get(1);
直前のMap型のfaild(sucsessed)CoverageStatusを作る時に，例えば通った行が一つもなくて，通らなかった行が10行だった場合，{(1 : 10), (2 : 0)}となるのではなく，{(1: 10)}となってしまうのでMapのkeyである2が存在しないことになってnullになります．
(keyの1が通らなかった行で2が通った行です．確かにわかりづらいのでenumに変えておきます)
{(1 : 10), (2 : 0)}みたいにできないか調べておきます．

2020-05-17 10:21 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            int numberOfSuccessedTestsNotCoveringStatement = successedCoverageStatus.get(1) == null ? 0 : successedCoverageStatus.get(1);
nullチェックの意図が分かりにくいので出来ればそのようにお願いします

2020-05-19 15:56 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +            //jacocoRuntime.startup(jacocoRuntimeData);
これも消していいやつ？

2020-11-13 06:58 UTC, Asada0815 reviewed
レビュー終わりました。

2020-11-13 06:58 UTC, Asada0815 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +                    if (t.getCoverages().stream().filter(c -> c.getName().equals(sourceFqn)).findFirst().isPresent()){
if文じゃなくて条件式をそのまま返すだけでいい気がする

2020-11-13 06:58 UTC, Asada0815 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +            Set<String> set = new HashSet<>(testNames);
ここの処理って多分重複を除外してると思うんだけど，streamのdistinctメソッドを使えたりしないかな

2020-11-13 06:58 UTC, Asada0815 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +        private boolean hasMassage = true;
変数名にerrorを含めた方が分かりやすいかも

2020-11-13 09:46 UTC, shuto410 requested changes
jacocoを使って正常なテストケースの選別するクラスを作るのを別イシューでお願いします（このPRは流石にデカ過ぎるので）
UnitTestExecutorの頭で一度だけ動かすような設計にすれば良さそう

2020-11-13 09:46 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/ExecutionTest.java
> +public class ExecutionTest {
Executionに情報量がないのでTestCaseとかの方がよさそう

2020-11-13 09:46 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/FaultLocalization.java
> +    default public List<ExecutionTest> getExecutionTests() {
getExecutedTestsの方が正確？

2020-11-13 09:46 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/statement/SuspiciousnessCollector.java
> +    public List<ExecutionTest> getExecutionTests() {
ここもgetExecutedTestsの方がいい？

2020-11-13 09:46 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/test/executor/TestExecutor.java
> +    default public TestExecutorResult exec(RepairConfiguration config, List<ExecutionTest> executionTests) {
実行するテスト一覧ならtestsToBeExecutedとかのがいいかも？

2020-11-16 09:04 UTC, Asada0815 approved these changes

2020-12-03 08:26 UTC, shuto410 approved these changes

2020-12-03 08:27 UTC, merged