パッチ候補のメモリ容量削減
posl/jProphet pull request #124
Opened 2020-07-20 08:16 UTC by Asada0815

2020-09-25 13:15 UTC, kyamatek commented
- LexicalPreservingPrinterと同様の動作をするメソッドをNodeUtilityに追加．元のLexicalPreservingPrinterはstaticな変数に値を追加し続けてしまうため，メモリを圧迫していた．
- FLが終わった段階で，失敗したテストが通ったファイルのみをCompilationUnitにして，リストにして保持しておく．
- PatchCandidateは，リストにしておいたCompilationUnitのノードと，修正後のノード(CompilationUnitの一部ではないもの)をDiffWithTypeとして保持する．それに伴って各operationの実装を変更．
- 実際にパッチを当ててテスト実行する際は，リストにしておいたCompilationUnitをクローンして，そのクローンに対して修正後のノードを置換(挿入)して実行する．テスト実行するたびに，javaのガベージコレクションによってクローンは削除される．
- PatchEvaluatorの微修正．Comparatorのcompareで，二つの値が等しい時には0を返すようにしないとエラーが出ることがあったので修正．

2020-09-25 13:22 UTC, kyamatek commented
- defects4jのmath75で生成されるパッチのサイズは一つあたり50byte~1000byteくらいに抑えられた(元々3Mbyteくらい)
- パッチが約70000個生成されても使用メモリは500MBくらい(元々，パッチ約3000個を生成して使用メモリが4GBくらいになってエラーが出てた)

2020-11-05 06:52 UTC, shuto410 requested changes

2020-11-05 06:52 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/operation/VariableReplacer.java
> +    public List<Node> replaceAllVariablesForStatement(Node targetNode, List<String> fieldNames, List<String> localVarNames,
docコメントお願いします

2020-11-05 06:52 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/JProphetMain.java
> +        final Map<FileLocator, CompilationUnit> fileLocatorMap = new AstGenerator().exec(suspiciousenesses, config.getTargetProject().getSrcFileLocators());
本体はCompilationUnitの方だと思うのでそっちを名前に組み込んだ方がいいと思う(targetFile)CompilaionUnit(or Cu?)Map?

2020-11-05 06:52 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/patch/DiffWithType.java
> +public class DiffWithType { //TODO: クラス名改善の余地あり
OperationDiffとかのがいいかも

2020-11-05 06:52 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/patch/DiffWithType.java
> +     * @param targetNodeAfterFix 修正部分のノードで，親ノードを持たない
getterの方にもこのdocが欲しい

2020-11-05 08:01 UTC, shuto410 approved these changes

2020-11-05 08:02 UTC, kyamatek approved these changes

2020-11-05 08:02 UTC, merged