Learning mode
posl/jProphet pull request #129
Opened 2020-08-10 14:13 UTC by shuto410

2020-10-14 08:03 UTC, kyamatek requested changes
レビュー終わりました．

2020-10-14 19:36 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/evaluator/PatchEvaluator.java
> +                for (int rank = 1; rank <= candidatesSortedBySuspiciousness.size(); rank++) {
んー確かに
ただ論文ではランクがそのまま使われているっぽいからこの実装にしたのよね
<img width="790" alt="スクリーンショット 2020-10-15 4 34 53" src="https://user-images.githubusercontent.com/22495089/96036707-d0c39680-0e9f-11eb-8e3b-037b0d9e6242.png">
実装の変更が楽そうだったら変えてみますわ

2020-10-16 05:43 UTC, Asada0815 requested changes

2020-10-16 05:43 UTC, Asada0815 commented on src/main/java/jp/posl/jprophet/evaluator/PatchEvaluator.java
> +                    }))
スコアが高い順に並べるのであれば， reversed() が必要だと思います．

2020-10-16 05:43 UTC, Asada0815 commented
レビュー終わりました．

2020-10-16 07:22 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/evaluator/PatchEvaluator.java
> +                    }))
思いっきりミスってた！ありがとう

2020-10-19 02:54 UTC, kyamatek approved these changes
Approve しました

2020-10-19 02:58 UTC, Asada0815 approved these changes

2020-10-19 04:34 UTC, merged