実行するテストケースの選別
posl/jProphet pull request #137
Opened 2020-11-27 08:46 UTC by kyamatek

TestExecutor の実行前に jacoco を使って正しく動くテストのみを取り出す

2020-12-16 06:03 UTC, Asada0815 approved these changes
レビュー終わりました．
特に問題はないと思います．

2020-12-18 00:36 UTC, shuto410 requested changes

2020-12-18 00:36 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +    public List<TestCase> getTestCases(RepairConfiguration config) {
"正しく動く"テストを"選ぶ"的なニュアンスがメソッド名にないので含めるといいと思う（filter〜とかselect〜とか？）

2020-12-18 00:36 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +            List<TestCase> testsToBeExecuted = new ArrayList<TestCase>();
このメソッドはあくまで正しく動くテストを選んでるだけなので，"正しく動くテスト"的な命名が欲しいです

2020-12-18 00:36 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +     */
このメソッドの存在理由（正しく動くor動かないテストが発生している経緯と判別手法？）をコメントで残して欲しい

2021-01-23 20:09 UTC, shuto410 commented on src/main/java/jp/posl/jprophet/fl/spectrumbased/coverage/CoverageCollector.java
> +            List<TestCase> testsToBeExecuted = new ArrayList<TestCase>();
このコメントは121行目のtestsToBeExecutedって変数名に対するコメントでした．
分かりづらくて申し訳なかったです

2021-01-24 19:04 UTC, shuto410 approved these changes

2021-01-25 03:04 UTC, merged